import { useState, useCallback } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger, TooltipProvider } from "@/components/ui/tooltip";
import { Rocket, Copy, Download, Check, ExternalLink, FileCode, Terminal, Globe } from "lucide-react";
import { toast } from "sonner";
import { exportTokens } from "@/lib/token-pipeline";
import { initializeExporters } from "@/lib/exporters";

initializeExporters();

interface DeployDialogProps {
  tokens: Record<string, any>;
  styleName: string;
  trigger?: React.ReactNode;
}

interface PlatformConfig {
  id: string;
  name: string;
  logo: string;
  color: string;
  description: string;
  docsUrl: string;
}

const PLATFORMS: PlatformConfig[] = [
  {
    id: 'vercel',
    name: 'Vercel',
    logo: '▲',
    color: 'bg-black text-white',
    description: 'Zero-config deployments for Next.js, React, and more',
    docsUrl: 'https://vercel.com/docs',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    logo: '◆',
    color: 'bg-[#00AD9F] text-white',
    description: 'Build, deploy, and scale modern web projects',
    docsUrl: 'https://docs.netlify.com/',
  },
];

function generateVercelConfig(styleName: string): string {
  return JSON.stringify({
    "$schema": "https://openapi.vercel.sh/vercel.json",
    "framework": null,
    "buildCommand": "npm run build",
    "outputDirectory": "dist",
    "env": {
      "STYLE_NAME": styleName,
    },
    "headers": [
      {
        "source": "/(.*)",
        "headers": [
          { "key": "X-Content-Type-Options", "value": "nosniff" },
          { "key": "X-Frame-Options", "value": "DENY" },
        ],
      },
    ],
  }, null, 2);
}

function generateNetlifyConfig(styleName: string): string {
  return `# Netlify configuration for ${styleName}
# Generated by Visual DNA Studio

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  STYLE_NAME = "${styleName}"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;
}

function generatePackageJson(styleName: string, tokens: Record<string, any>): string {
  const safeName = styleName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
  return JSON.stringify({
    "name": safeName + "-theme",
    "version": "1.0.0",
    "description": `Design tokens for ${styleName}`,
    "main": "tokens.css",
    "scripts": {
      "build": "echo 'Tokens ready for deployment'",
      "dev": "echo 'Development mode'",
    },
    "keywords": ["design-tokens", "visual-dna", "theme"],
    "license": "MIT",
  }, null, 2);
}

function generateReadme(styleName: string, platform: string): string {
  const platformName = platform === 'vercel' ? 'Vercel' : 'Netlify';
  const deployCommand = platform === 'vercel' ? 'vercel' : 'netlify deploy --prod';
  
  return `# ${styleName} Design Tokens

Generated by Visual DNA Studio

## Quick Deploy to ${platformName}

### Prerequisites
- Node.js 18+ installed
- ${platformName} CLI installed (\`npm i -g ${platform}\`)
- ${platformName} account

### Steps

1. **Initialize the project:**
   \`\`\`bash
   npm install
   \`\`\`

2. **Deploy:**
   \`\`\`bash
   ${deployCommand}
   \`\`\`

3. **Follow the CLI prompts** to link your ${platformName} account

## Files Included

- \`tokens.css\` - CSS custom properties
- \`tokens.json\` - W3C DTCG format tokens
- \`theme.ts\` - TypeScript theme object
- \`${platform === 'vercel' ? 'vercel.json' : 'netlify.toml'}\` - Platform configuration

## Usage

Import the CSS variables in your project:

\`\`\`css
@import url('./tokens.css');
\`\`\`

Or use the TypeScript theme:

\`\`\`typescript
import { theme } from './theme';
\`\`\`

---

Created with [Visual DNA Studio](https://visualdna.studio)
`;
}

export function DeployDialog({ tokens, styleName, trigger }: DeployDialogProps) {
  const [open, setOpen] = useState(false);
  const [selectedPlatform, setSelectedPlatform] = useState<string>('vercel');
  const [copiedItem, setCopiedItem] = useState<string | null>(null);
  const [deploying, setDeploying] = useState(false);

  const copyToClipboard = useCallback(async (text: string, itemId: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedItem(itemId);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopiedItem(null), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  }, []);

  const createZipBundle = useCallback((files: { name: string; content: string }[]): Blob => {
    const encoder = new TextEncoder();
    const parts: Uint8Array[] = [];
    const centralDirectory: Uint8Array[] = [];
    let offset = 0;

    for (const file of files) {
      const nameBytes = encoder.encode(file.name);
      const contentBytes = encoder.encode(file.content);
      
      const localHeader = new Uint8Array(30 + nameBytes.length);
      const view = new DataView(localHeader.buffer);
      
      view.setUint32(0, 0x04034b50, true);
      view.setUint16(4, 20, true);
      view.setUint16(6, 0, true);
      view.setUint16(8, 0, true);
      view.setUint16(10, 0, true);
      view.setUint16(12, 0, true);
      view.setUint32(14, 0, true);
      view.setUint32(18, contentBytes.length, true);
      view.setUint32(22, contentBytes.length, true);
      view.setUint16(26, nameBytes.length, true);
      view.setUint16(28, 0, true);
      localHeader.set(nameBytes, 30);
      
      parts.push(localHeader);
      parts.push(contentBytes);
      
      const cdEntry = new Uint8Array(46 + nameBytes.length);
      const cdView = new DataView(cdEntry.buffer);
      
      cdView.setUint32(0, 0x02014b50, true);
      cdView.setUint16(4, 20, true);
      cdView.setUint16(6, 20, true);
      cdView.setUint16(8, 0, true);
      cdView.setUint16(10, 0, true);
      cdView.setUint16(12, 0, true);
      cdView.setUint16(14, 0, true);
      cdView.setUint32(16, 0, true);
      cdView.setUint32(20, contentBytes.length, true);
      cdView.setUint32(24, contentBytes.length, true);
      cdView.setUint16(28, nameBytes.length, true);
      cdView.setUint16(30, 0, true);
      cdView.setUint16(32, 0, true);
      cdView.setUint16(34, 0, true);
      cdView.setUint16(36, 0, true);
      cdView.setUint32(38, 0, true);
      cdView.setUint32(42, offset, true);
      cdEntry.set(nameBytes, 46);
      
      centralDirectory.push(cdEntry);
      offset += localHeader.length + contentBytes.length;
    }
    
    const cdOffset = offset;
    let cdSize = 0;
    for (const cd of centralDirectory) {
      parts.push(cd);
      cdSize += cd.length;
    }
    
    const endRecord = new Uint8Array(22);
    const endView = new DataView(endRecord.buffer);
    endView.setUint32(0, 0x06054b50, true);
    endView.setUint16(4, 0, true);
    endView.setUint16(6, 0, true);
    endView.setUint16(8, files.length, true);
    endView.setUint16(10, files.length, true);
    endView.setUint32(12, cdSize, true);
    endView.setUint32(16, cdOffset, true);
    endView.setUint16(20, 0, true);
    parts.push(endRecord);
    
    return new Blob(parts, { type: 'application/zip' });
  }, []);

  const handleDownloadBundle = useCallback(async () => {
    setDeploying(true);
    
    try {
      const platform = selectedPlatform;
      const safeName = styleName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
      
      const cssResult = exportTokens(tokens, styleName, 'css', {});
      const cssContent = typeof cssResult.content === 'string' ? cssResult.content : new TextDecoder().decode(cssResult.content);
      
      const dtcgResult = exportTokens(tokens, styleName, 'dtcg-json', {});
      const dtcgContent = typeof dtcgResult.content === 'string' ? dtcgResult.content : new TextDecoder().decode(dtcgResult.content);
      
      let themeContent = '';
      try {
        const nextResult = exportTokens(tokens, styleName, 'nextjs', { cssInJs: true });
        themeContent = typeof nextResult.content === 'string' ? nextResult.content : new TextDecoder().decode(nextResult.content);
      } catch {
        themeContent = `// Theme for ${styleName}\nexport const theme = {};\n`;
      }
      
      const configContent = platform === 'vercel' 
        ? generateVercelConfig(styleName)
        : generateNetlifyConfig(styleName);
      const configFilename = platform === 'vercel' ? 'vercel.json' : 'netlify.toml';
      
      const packageJson = generatePackageJson(styleName, tokens);
      const readme = generateReadme(styleName, platform);
      
      const files = [
        { name: 'tokens.css', content: cssContent },
        { name: 'tokens.json', content: dtcgContent },
        { name: 'theme.ts', content: themeContent },
        { name: configFilename, content: configContent },
        { name: 'package.json', content: packageJson },
        { name: 'README.md', content: readme },
      ];
      
      const zipBlob = createZipBundle(files);
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${safeName}-${platform}-bundle.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success(`Downloaded ${platform === 'vercel' ? 'Vercel' : 'Netlify'} deployment bundle`);
    } catch (error) {
      console.error('Failed to generate bundle:', error);
      toast.error('Failed to generate deployment bundle');
    } finally {
      setDeploying(false);
    }
  }, [selectedPlatform, styleName, tokens, createZipBundle]);

  const platform = PLATFORMS.find(p => p.id === selectedPlatform)!;
  const configContent = selectedPlatform === 'vercel' 
    ? generateVercelConfig(styleName)
    : generateNetlifyConfig(styleName);
  const configFilename = selectedPlatform === 'vercel' ? 'vercel.json' : 'netlify.toml';

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" size="sm" data-testid="button-deploy">
            <Rocket className="w-4 h-4 mr-2" />
            Deploy
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Rocket className="w-5 h-5" />
            One-Click Deploy
          </DialogTitle>
          <DialogDescription>
            Deploy your design tokens to popular hosting platforms
          </DialogDescription>
        </DialogHeader>

        <Tabs value={selectedPlatform} onValueChange={setSelectedPlatform} className="flex-1">
          <TabsList className="grid w-full grid-cols-2">
            {PLATFORMS.map(p => (
              <TabsTrigger key={p.id} value={p.id} className="flex items-center gap-2" data-testid={`tab-${p.id}`}>
                <span className={`w-5 h-5 rounded flex items-center justify-center text-xs font-bold ${p.color}`}>
                  {p.logo}
                </span>
                {p.name}
              </TabsTrigger>
            ))}
          </TabsList>

          {PLATFORMS.map(p => (
            <TabsContent key={p.id} value={p.id} className="mt-4 space-y-4">
              <div className="flex items-start gap-3 p-4 rounded-lg border border-border bg-muted/20">
                <span className={`w-10 h-10 rounded-lg flex items-center justify-center text-lg font-bold ${p.color}`}>
                  {p.logo}
                </span>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{p.name}</h3>
                    <a 
                      href={p.docsUrl} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-muted-foreground hover:text-foreground"
                    >
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                  <p className="text-sm text-muted-foreground">{p.description}</p>
                </div>
              </div>

              <div className="space-y-3">
                <h4 className="text-sm font-medium flex items-center gap-2">
                  <FileCode className="w-4 h-4" />
                  Configuration File
                  <Badge variant="outline" className="text-[10px] font-mono">{configFilename}</Badge>
                </h4>
                
                <div className="relative">
                  <ScrollArea className="h-48 rounded-md border border-border bg-muted/30">
                    <pre className="p-4 text-xs font-mono whitespace-pre-wrap">{configContent}</pre>
                  </ScrollArea>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="absolute top-2 right-2 h-7 w-7"
                          onClick={() => copyToClipboard(configContent, 'config')}
                          data-testid={`button-copy-config-${p.id}`}
                        >
                          {copiedItem === 'config' ? (
                            <Check className="w-3.5 h-3.5 text-green-500" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </Button>
                      </TooltipTrigger>
                      <TooltipContent>Copy configuration</TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
              </div>

              <div className="space-y-3">
                <h4 className="text-sm font-medium flex items-center gap-2">
                  <Terminal className="w-4 h-4" />
                  Quick Start
                </h4>
                
                <div className="space-y-2">
                  {[
                    { step: 1, cmd: `npm i -g ${p.id}`, desc: `Install ${p.name} CLI` },
                    { step: 2, cmd: p.id === 'vercel' ? 'vercel login' : 'netlify login', desc: 'Authenticate' },
                    { step: 3, cmd: p.id === 'vercel' ? 'vercel' : 'netlify deploy --prod', desc: 'Deploy' },
                  ].map(({ step, cmd, desc }) => (
                    <div key={step} className="flex items-center gap-3 p-2 rounded border border-border/50 bg-muted/10">
                      <Badge variant="secondary" className="w-6 h-6 rounded-full p-0 flex items-center justify-center text-xs">
                        {step}
                      </Badge>
                      <code className="flex-1 text-xs font-mono bg-muted/50 px-2 py-1 rounded">{cmd}</code>
                      <span className="text-xs text-muted-foreground">{desc}</span>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-6 w-6"
                              onClick={() => copyToClipboard(cmd, `cmd-${step}`)}
                              data-testid={`button-copy-cmd-${step}`}
                            >
                              {copiedItem === `cmd-${step}` ? (
                                <Check className="w-3 h-3 text-green-500" />
                              ) : (
                                <Copy className="w-3 h-3" />
                              )}
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>Copy command</TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </div>
                  ))}
                </div>
              </div>
            </TabsContent>
          ))}
        </Tabs>

        <div className="flex items-center justify-between pt-4 border-t border-border mt-4">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Globe className="w-4 h-4" />
            <span>Includes tokens, config, and README</span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setOpen(false)}
              data-testid="button-cancel-deploy"
            >
              Cancel
            </Button>
            <Button
              size="sm"
              onClick={handleDownloadBundle}
              disabled={deploying}
              data-testid="button-download-bundle"
            >
              {deploying ? (
                "Preparing..."
              ) : (
                <>
                  <Download className="w-4 h-4 mr-2" />
                  Download {platform.name} Bundle
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
