import { useState, useCallback, useMemo } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger, TooltipProvider } from "@/components/ui/tooltip";
import { Rocket, Copy, Download, Check, ExternalLink, FileCode, Terminal, Globe, Zap, Github, Cloud, ArrowRight } from "lucide-react";
import { toast } from "sonner";
import { exportTokens } from "@/lib/token-pipeline";
import { initializeExporters } from "@/lib/exporters";

initializeExporters();

interface DeployDialogProps {
  tokens: Record<string, any>;
  styleName: string;
  trigger?: React.ReactNode;
}

interface PlatformConfig {
  id: string;
  name: string;
  logo: string;
  color: string;
  description: string;
  docsUrl: string;
  oneClickUrl?: string;
  cliInstall: string;
  loginCmd: string;
  deployCmd: string;
}

const PLATFORMS: PlatformConfig[] = [
  {
    id: 'vercel',
    name: 'Vercel',
    logo: '▲',
    color: 'bg-black text-white',
    description: 'Zero-config deployments for Next.js, React, and more',
    docsUrl: 'https://vercel.com/docs',
    oneClickUrl: 'https://vercel.com/new',
    cliInstall: 'npm i -g vercel',
    loginCmd: 'vercel login',
    deployCmd: 'vercel --prod',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    logo: '◆',
    color: 'bg-[#00AD9F] text-white',
    description: 'Build, deploy, and scale modern web projects',
    docsUrl: 'https://docs.netlify.com/',
    oneClickUrl: 'https://app.netlify.com/drop',
    cliInstall: 'npm i -g netlify-cli',
    loginCmd: 'netlify login',
    deployCmd: 'netlify deploy --prod',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Pages',
    logo: '☁',
    color: 'bg-[#F6821F] text-white',
    description: 'Fast, secure sites with unlimited bandwidth',
    docsUrl: 'https://developers.cloudflare.com/pages/',
    oneClickUrl: 'https://dash.cloudflare.com/?to=/:account/pages/new',
    cliInstall: 'npm i -g wrangler',
    loginCmd: 'wrangler login',
    deployCmd: 'wrangler pages deploy dist',
  },
  {
    id: 'railway',
    name: 'Railway',
    logo: '🚂',
    color: 'bg-[#0B0D0E] text-white',
    description: 'Deploy from GitHub or CLI in seconds',
    docsUrl: 'https://docs.railway.app/',
    oneClickUrl: 'https://railway.app/new',
    cliInstall: 'npm i -g @railway/cli',
    loginCmd: 'railway login',
    deployCmd: 'railway up',
  },
  {
    id: 'render',
    name: 'Render',
    logo: '◉',
    color: 'bg-[#46E3B7] text-black',
    description: 'Cloud application hosting with free SSL',
    docsUrl: 'https://render.com/docs',
    oneClickUrl: 'https://dashboard.render.com/select-repo?type=static',
    cliInstall: 'npm i -g render-cli',
    loginCmd: 'render login',
    deployCmd: 'render deploy',
  },
];

function generateVercelConfig(styleName: string): string {
  return JSON.stringify({
    "$schema": "https://openapi.vercel.sh/vercel.json",
    "framework": null,
    "buildCommand": "npm run build",
    "outputDirectory": "dist",
    "env": {
      "STYLE_NAME": styleName,
    },
    "headers": [
      {
        "source": "/(.*)",
        "headers": [
          { "key": "X-Content-Type-Options", "value": "nosniff" },
          { "key": "X-Frame-Options", "value": "DENY" },
        ],
      },
    ],
  }, null, 2);
}

function generateNetlifyConfig(styleName: string): string {
  return `# Netlify configuration for ${styleName}
# Generated by Visual DNA Studio

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  STYLE_NAME = "${styleName}"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;
}

function generatePackageJson(styleName: string, tokens: Record<string, any>): string {
  const safeName = styleName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
  return JSON.stringify({
    "name": safeName + "-theme",
    "version": "1.0.0",
    "description": `Design tokens for ${styleName}`,
    "main": "tokens.css",
    "scripts": {
      "build": "echo 'Tokens ready for deployment'",
      "dev": "echo 'Development mode'",
    },
    "keywords": ["design-tokens", "visual-dna", "theme"],
    "license": "MIT",
  }, null, 2);
}

function generateReadme(styleName: string, platform: string): string {
  const platformConfig = PLATFORMS.find(p => p.id === platform);
  const platformName = platformConfig?.name || platform;
  const deployCommand = platformConfig?.deployCmd || `${platform} deploy`;
  const cliInstall = platformConfig?.cliInstall || `npm i -g ${platform}`;
  
  return `# ${styleName} Design Tokens

Generated by Visual DNA Studio

## Quick Deploy to ${platformName}

### Prerequisites
- Node.js 18+ installed
- ${platformName} CLI installed (\`${cliInstall}\`)
- ${platformName} account

### Steps

1. **Extract the bundle:**
   \`\`\`bash
   unzip ${styleName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${platform}-bundle.zip -d ${styleName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-theme
   cd ${styleName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-theme
   \`\`\`

2. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

3. **Deploy:**
   \`\`\`bash
   ${deployCommand}
   \`\`\`

4. **Follow the CLI prompts** to link your ${platformName} account

## One-Click Deploy Option

You can also drag and drop the \`dist\` folder directly to:
${platformConfig?.oneClickUrl ? `- ${platformConfig.oneClickUrl}` : '- Your platform dashboard'}

## Files Included

- \`tokens.css\` - CSS custom properties
- \`tokens.json\` - W3C DTCG format tokens
- \`theme.ts\` - TypeScript theme object
- \`index.html\` - Preview page with your tokens
- Platform configuration file

## Usage

Import the CSS variables in your project:

\`\`\`css
@import url('./tokens.css');
\`\`\`

Or use the TypeScript theme:

\`\`\`typescript
import { theme } from './theme';
\`\`\`

## Token Categories

This bundle includes design tokens for:
- Colors (primary, secondary, accent, neutrals)
- Typography (font families, sizes, weights)
- Spacing (consistent spacing scale)
- Border radius (rounded corners)
- Shadows (elevation levels)
- Motion (animations and transitions)

---

Created with [Visual DNA Studio](https://visualdna.studio)
`;
}

function generateIndexHtml(styleName: string, tokens: Record<string, any>): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${styleName} - Design Tokens</title>
  <link rel="stylesheet" href="tokens.css">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { 
      font-family: var(--typography-font-family-sans, system-ui, sans-serif);
      background: var(--color-background, #fafafa);
      color: var(--color-text, #1a1a1a);
      padding: 2rem;
      min-height: 100vh;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    h1 { 
      font-size: 2.5rem; 
      margin-bottom: 0.5rem;
      color: var(--color-primary, #3b82f6);
    }
    .subtitle { 
      color: var(--color-text-muted, #666); 
      margin-bottom: 2rem;
    }
    .section { 
      background: var(--color-surface, white);
      border-radius: var(--border-radius-lg, 12px);
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      box-shadow: var(--shadow-md, 0 4px 6px rgba(0,0,0,0.1));
    }
    .section-title { 
      font-size: 1.25rem;
      margin-bottom: 1rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .color-grid { 
      display: grid; 
      grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); 
      gap: 1rem; 
    }
    .color-swatch {
      aspect-ratio: 1;
      border-radius: var(--border-radius-md, 8px);
      display: flex;
      align-items: flex-end;
      padding: 0.5rem;
      font-size: 0.75rem;
      color: white;
      text-shadow: 0 1px 2px rgba(0,0,0,0.5);
    }
    .typography-sample { margin: 0.5rem 0; }
    .spacing-row { 
      display: flex; 
      align-items: center; 
      gap: 1rem; 
      margin: 0.5rem 0;
    }
    .spacing-bar { 
      height: 1.5rem; 
      background: var(--color-primary, #3b82f6);
      border-radius: 4px;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      padding: 0.25rem 0.75rem;
      background: var(--color-primary, #3b82f6);
      color: white;
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 500;
    }
    footer { 
      text-align: center; 
      margin-top: 3rem; 
      color: var(--color-text-muted, #666);
      font-size: 0.875rem;
    }
    footer a { color: var(--color-primary, #3b82f6); }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${styleName}</h1>
      <p class="subtitle">Design Tokens Preview</p>
    </header>

    <div class="section">
      <h2 class="section-title">🎨 Colors</h2>
      <div class="color-grid" id="colors"></div>
    </div>

    <div class="section">
      <h2 class="section-title">📝 Typography</h2>
      <div id="typography"></div>
    </div>

    <div class="section">
      <h2 class="section-title">📏 Spacing</h2>
      <div id="spacing"></div>
    </div>

    <div class="section">
      <h2 class="section-title">⬛ Border Radius</h2>
      <div id="radius" style="display: flex; gap: 1rem; flex-wrap: wrap;"></div>
    </div>

    <footer>
      <p>Generated by <a href="https://visualdna.studio" target="_blank">Visual DNA Studio</a></p>
    </footer>
  </div>

  <script>
    const style = getComputedStyle(document.documentElement);
    
    const colorVars = ['primary', 'secondary', 'tertiary', 'accent', 'background', 'surface'];
    const colorsEl = document.getElementById('colors');
    colorVars.forEach(name => {
      const value = style.getPropertyValue('--color-' + name).trim();
      if (value) {
        const div = document.createElement('div');
        div.className = 'color-swatch';
        div.style.backgroundColor = value;
        div.textContent = name;
        colorsEl.appendChild(div);
      }
    });

    const typographyEl = document.getElementById('typography');
    const sizes = ['sm', 'base', 'lg', 'xl', '2xl', '3xl'];
    sizes.forEach(size => {
      const p = document.createElement('p');
      p.className = 'typography-sample';
      p.style.fontSize = 'var(--typography-font-size-' + size + ', 1rem)';
      p.textContent = size.toUpperCase() + ' - The quick brown fox jumps over the lazy dog';
      typographyEl.appendChild(p);
    });

    const spacingEl = document.getElementById('spacing');
    ['1', '2', '3', '4', '6', '8'].forEach(size => {
      const row = document.createElement('div');
      row.className = 'spacing-row';
      row.innerHTML = '<span style="width: 2rem;">' + size + '</span><div class="spacing-bar" style="width: var(--spacing-' + size + ', ' + (parseInt(size) * 4) + 'px);"></div>';
      spacingEl.appendChild(row);
    });

    const radiusEl = document.getElementById('radius');
    ['sm', 'md', 'lg', 'xl', 'full'].forEach(size => {
      const div = document.createElement('div');
      div.style.cssText = 'width: 80px; height: 80px; background: var(--color-primary, #3b82f6); border-radius: var(--border-radius-' + size + ', 8px); display: flex; align-items: center; justify-content: center; color: white; font-size: 0.75rem;';
      div.textContent = size;
      radiusEl.appendChild(div);
    });
  </script>
</body>
</html>`;
}

export function DeployDialog({ tokens, styleName, trigger }: DeployDialogProps) {
  const [open, setOpen] = useState(false);
  const [selectedPlatform, setSelectedPlatform] = useState<string>('vercel');
  const [copiedItem, setCopiedItem] = useState<string | null>(null);
  const [deploying, setDeploying] = useState(false);

  const copyToClipboard = useCallback(async (text: string, itemId: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedItem(itemId);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopiedItem(null), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  }, []);

  const createZipBundle = useCallback((files: { name: string; content: string }[]): Blob => {
    const encoder = new TextEncoder();
    const parts: Uint8Array[] = [];
    const centralDirectory: Uint8Array[] = [];
    let offset = 0;

    for (const file of files) {
      const nameBytes = encoder.encode(file.name);
      const contentBytes = encoder.encode(file.content);
      
      const localHeader = new Uint8Array(30 + nameBytes.length);
      const view = new DataView(localHeader.buffer);
      
      view.setUint32(0, 0x04034b50, true);
      view.setUint16(4, 20, true);
      view.setUint16(6, 0, true);
      view.setUint16(8, 0, true);
      view.setUint16(10, 0, true);
      view.setUint16(12, 0, true);
      view.setUint32(14, 0, true);
      view.setUint32(18, contentBytes.length, true);
      view.setUint32(22, contentBytes.length, true);
      view.setUint16(26, nameBytes.length, true);
      view.setUint16(28, 0, true);
      localHeader.set(nameBytes, 30);
      
      parts.push(localHeader);
      parts.push(contentBytes);
      
      const cdEntry = new Uint8Array(46 + nameBytes.length);
      const cdView = new DataView(cdEntry.buffer);
      
      cdView.setUint32(0, 0x02014b50, true);
      cdView.setUint16(4, 20, true);
      cdView.setUint16(6, 20, true);
      cdView.setUint16(8, 0, true);
      cdView.setUint16(10, 0, true);
      cdView.setUint16(12, 0, true);
      cdView.setUint16(14, 0, true);
      cdView.setUint32(16, 0, true);
      cdView.setUint32(20, contentBytes.length, true);
      cdView.setUint32(24, contentBytes.length, true);
      cdView.setUint16(28, nameBytes.length, true);
      cdView.setUint16(30, 0, true);
      cdView.setUint16(32, 0, true);
      cdView.setUint16(34, 0, true);
      cdView.setUint16(36, 0, true);
      cdView.setUint32(38, 0, true);
      cdView.setUint32(42, offset, true);
      cdEntry.set(nameBytes, 46);
      
      centralDirectory.push(cdEntry);
      offset += localHeader.length + contentBytes.length;
    }
    
    const cdOffset = offset;
    let cdSize = 0;
    for (const cd of centralDirectory) {
      parts.push(cd);
      cdSize += cd.length;
    }
    
    const endRecord = new Uint8Array(22);
    const endView = new DataView(endRecord.buffer);
    endView.setUint32(0, 0x06054b50, true);
    endView.setUint16(4, 0, true);
    endView.setUint16(6, 0, true);
    endView.setUint16(8, files.length, true);
    endView.setUint16(10, files.length, true);
    endView.setUint32(12, cdSize, true);
    endView.setUint32(16, cdOffset, true);
    endView.setUint16(20, 0, true);
    parts.push(endRecord);
    
    return new Blob(parts, { type: 'application/zip' });
  }, []);

  const generatePlatformConfig = useCallback((platformId: string): { content: string; filename: string } => {
    switch (platformId) {
      case 'vercel':
        return { content: generateVercelConfig(styleName), filename: 'vercel.json' };
      case 'netlify':
        return { content: generateNetlifyConfig(styleName), filename: 'netlify.toml' };
      case 'cloudflare':
        return {
          content: `name = "${styleName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}"
compatibility_date = "${new Date().toISOString().split('T')[0]}"

[site]
bucket = "./dist"`,
          filename: 'wrangler.toml',
        };
      case 'railway':
        return {
          content: JSON.stringify({
            $schema: 'https://railway.app/railway.schema.json',
            build: { builder: 'NIXPACKS' },
            deploy: { restartPolicyType: 'ON_FAILURE' },
          }, null, 2),
          filename: 'railway.json',
        };
      case 'render':
        return {
          content: `services:
  - type: web
    name: ${styleName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}-tokens
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist`,
          filename: 'render.yaml',
        };
      default:
        return { content: generateVercelConfig(styleName), filename: 'vercel.json' };
    }
  }, [styleName]);

  const handleDownloadBundle = useCallback(async () => {
    setDeploying(true);
    
    try {
      const platform = selectedPlatform;
      const safeName = styleName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
      
      const cssResult = exportTokens(tokens, styleName, 'css', {});
      const cssContent = typeof cssResult.content === 'string' ? cssResult.content : new TextDecoder().decode(cssResult.content);
      
      const dtcgResult = exportTokens(tokens, styleName, 'dtcg-json', {});
      const dtcgContent = typeof dtcgResult.content === 'string' ? dtcgResult.content : new TextDecoder().decode(dtcgResult.content);
      
      let themeContent = '';
      try {
        const nextResult = exportTokens(tokens, styleName, 'nextjs', { cssInJs: true });
        themeContent = typeof nextResult.content === 'string' ? nextResult.content : new TextDecoder().decode(nextResult.content);
      } catch {
        themeContent = `// Theme for ${styleName}\nexport const theme = {};\n`;
      }
      
      const { content: configContent, filename: configFilename } = generatePlatformConfig(platform);
      const packageJson = generatePackageJson(styleName, tokens);
      const readme = generateReadme(styleName, platform);
      const indexHtml = generateIndexHtml(styleName, tokens);
      
      const files = [
        { name: 'dist/index.html', content: indexHtml },
        { name: 'dist/tokens.css', content: cssContent },
        { name: 'tokens.css', content: cssContent },
        { name: 'tokens.json', content: dtcgContent },
        { name: 'theme.ts', content: themeContent },
        { name: configFilename, content: configContent },
        { name: 'package.json', content: packageJson },
        { name: 'README.md', content: readme },
      ];
      
      const zipBlob = createZipBundle(files);
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${safeName}-${platform}-bundle.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      const platformName = PLATFORMS.find(p => p.id === platform)?.name || platform;
      toast.success(`Downloaded ${platformName} deployment bundle`);
    } catch (error) {
      console.error('Failed to generate bundle:', error);
      toast.error('Failed to generate deployment bundle');
    } finally {
      setDeploying(false);
    }
  }, [selectedPlatform, styleName, tokens, createZipBundle, generatePlatformConfig]);

  const handleOneClickDeploy = useCallback((platform: PlatformConfig) => {
    if (platform.oneClickUrl) {
      window.open(platform.oneClickUrl, '_blank', 'noopener,noreferrer');
      toast.info(`Opening ${platform.name}. Download the bundle first, then upload it there.`);
    }
  }, []);

  const platform = PLATFORMS.find(p => p.id === selectedPlatform)!;
  const { content: configContent, filename: configFilename } = useMemo(
    () => generatePlatformConfig(selectedPlatform),
    [generatePlatformConfig, selectedPlatform]
  );

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" size="sm" data-testid="button-deploy">
            <Rocket className="w-4 h-4 mr-2" />
            Deploy
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Rocket className="w-5 h-5" />
            One-Click Deploy
          </DialogTitle>
          <DialogDescription>
            Deploy your design tokens to popular hosting platforms
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="flex-1 min-h-0">
        <Tabs value={selectedPlatform} onValueChange={setSelectedPlatform} className="flex-1">
          <TabsList className="grid w-full grid-cols-5 h-auto gap-1 p-1">
            {PLATFORMS.map(p => (
              <TabsTrigger 
                key={p.id} 
                value={p.id} 
                className="flex flex-col items-center gap-1 py-2 px-2 text-xs" 
                data-testid={`tab-${p.id}`}
              >
                <span className={`w-6 h-6 rounded flex items-center justify-center text-sm font-bold ${p.color}`}>
                  {p.logo}
                </span>
                <span className="truncate max-w-full">{p.name.split(' ')[0]}</span>
              </TabsTrigger>
            ))}
          </TabsList>

          {PLATFORMS.map(p => (
            <TabsContent key={p.id} value={p.id} className="mt-4 space-y-4">
              <div className="flex items-start gap-3 p-4 rounded-lg border border-border bg-muted/20">
                <span className={`w-10 h-10 rounded-lg flex items-center justify-center text-lg font-bold ${p.color}`}>
                  {p.logo}
                </span>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{p.name}</h3>
                    <a 
                      href={p.docsUrl} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-muted-foreground hover:text-foreground"
                    >
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                  <p className="text-sm text-muted-foreground">{p.description}</p>
                </div>
              </div>

              <div className="space-y-3">
                <h4 className="text-sm font-medium flex items-center gap-2">
                  <FileCode className="w-4 h-4" />
                  Configuration File
                  <Badge variant="outline" className="text-[10px] font-mono">{configFilename}</Badge>
                </h4>
                
                <div className="relative">
                  <ScrollArea className="h-48 rounded-md border border-border bg-muted/30">
                    <pre className="p-4 text-xs font-mono whitespace-pre-wrap">{configContent}</pre>
                  </ScrollArea>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="absolute top-2 right-2 h-7 w-7"
                          onClick={() => copyToClipboard(configContent, 'config')}
                          data-testid={`button-copy-config-${p.id}`}
                        >
                          {copiedItem === 'config' ? (
                            <Check className="w-3.5 h-3.5 text-green-500" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </Button>
                      </TooltipTrigger>
                      <TooltipContent>Copy configuration</TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
              </div>

              <div className="space-y-3">
                <h4 className="text-sm font-medium flex items-center gap-2">
                  <Terminal className="w-4 h-4" />
                  Quick Start
                </h4>
                
                <div className="space-y-2">
                  {[
                    { step: 1, cmd: p.cliInstall, desc: `Install CLI` },
                    { step: 2, cmd: p.loginCmd, desc: 'Authenticate' },
                    { step: 3, cmd: p.deployCmd, desc: 'Deploy' },
                  ].map(({ step, cmd, desc }) => (
                    <div key={step} className="flex items-center gap-3 p-2 rounded border border-border/50 bg-muted/10">
                      <Badge variant="secondary" className="w-6 h-6 rounded-full p-0 flex items-center justify-center text-xs">
                        {step}
                      </Badge>
                      <code className="flex-1 text-xs font-mono bg-muted/50 px-2 py-1 rounded truncate">{cmd}</code>
                      <span className="text-xs text-muted-foreground whitespace-nowrap">{desc}</span>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-6 w-6"
                              onClick={() => copyToClipboard(cmd, `cmd-${step}`)}
                              data-testid={`button-copy-cmd-${step}`}
                            >
                              {copiedItem === `cmd-${step}` ? (
                                <Check className="w-3 h-3 text-green-500" />
                              ) : (
                                <Copy className="w-3 h-3" />
                              )}
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>Copy command</TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </div>
                  ))}
                </div>
              </div>

              {p.oneClickUrl && (
                <div className="p-4 rounded-lg border border-dashed border-primary/50 bg-primary/5">
                  <div className="flex items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-full bg-primary/10">
                        <Zap className="w-5 h-5 text-primary" />
                      </div>
                      <div>
                        <h4 className="font-medium text-sm">One-Click Deploy</h4>
                        <p className="text-xs text-muted-foreground">
                          Drag & drop the dist folder directly to {p.name}
                        </p>
                      </div>
                    </div>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleOneClickDeploy(p)}
                      data-testid={`button-one-click-${p.id}`}
                    >
                      <ExternalLink className="w-4 h-4 mr-2" />
                      Open {p.name}
                    </Button>
                  </div>
                </div>
              )}
            </TabsContent>
          ))}
        </Tabs>
        </ScrollArea>

        <div className="flex flex-col gap-3 pt-4 border-t border-border mt-4">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Cloud className="w-4 h-4" />
            <span>Bundle includes: tokens.css, tokens.json, theme.ts, index.html, config, README</span>
          </div>
          <div className="flex items-center justify-between">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setOpen(false)}
              data-testid="button-cancel-deploy"
            >
              Cancel
            </Button>
            <div className="flex items-center gap-2">
              {platform.oneClickUrl && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleOneClickDeploy(platform)}
                  data-testid="button-open-platform"
                >
                  <ExternalLink className="w-4 h-4 mr-2" />
                  Open {platform.name}
                </Button>
              )}
              <Button
                size="sm"
                onClick={handleDownloadBundle}
                disabled={deploying}
                data-testid="button-download-bundle"
              >
                {deploying ? (
                  "Preparing..."
                ) : (
                  <>
                    <Download className="w-4 h-4 mr-2" />
                    Download Bundle
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
