/**
 * CSS Variables Exporter
 * 
 * Exports tokens as CSS custom properties.
 */

import type { ExporterDefinition, NormalizedTokenSet } from '../token-pipeline';
import { sanitizeCssName, parseColor, rgbaToCSS, dimensionToCSS } from '../token-pipeline';

export const exportCSS: ExporterDefinition = {
  id: 'css',
  name: 'CSS Variables',
  description: 'CSS custom properties for web projects. Works with any web framework.',
  category: 'web',
  extension: 'css',
  mimeType: 'text/css',
  isBinary: false,
  serverSide: false,
  subOptions: [
    {
      id: 'selector',
      label: 'Root selector',
      type: 'select',
      default: ':root',
      options: [
        { value: ':root', label: ':root' },
        { value: ':host', label: ':host (Web Components)' },
        { value: '.theme', label: '.theme (class-based)' },
      ],
    },
  ],
  export: (tokens: NormalizedTokenSet, options?: Record<string, any>): string => {
    const selector = options?.selector ?? ':root';
    
    const lines: string[] = [
      `/* Design Tokens: ${tokens.name} */`,
      `/* Generated by Visual DNA Studio */`,
      `/* W3C DTCG compliant - ${tokens.metadata.exportedAt} */`,
      '',
      `${selector} {`,
    ];
    
    for (const token of tokens.tokens) {
      const name = token.path.map(sanitizeCssName).join('-');
      const cssValue = formatCSSValue(token.value, token.type);
      
      if (token.description) {
        lines.push(`  /* ${token.description} */`);
      }
      lines.push(`  --${name}: ${cssValue};`);
    }
    
    lines.push('}');
    return lines.join('\n');
  },
};

function formatCSSValue(value: any, type: string): string {
  if (type === 'color' && typeof value === 'string') {
    const parsed = parseColor(value);
    if (parsed) {
      return rgbaToCSS(parsed);
    }
  }
  
  if (type === 'dimension') {
    return dimensionToCSS(value);
  }
  
  if (typeof value === 'string') {
    if (/^#[0-9a-fA-F]{3,8}$/.test(value)) return value;
    if (/^(rgb|hsl|oklch)/.test(value)) return value;
    if (/^-?\d+(\.\d+)?(px|rem|em|%|vw|vh|deg|s|ms)?$/.test(value)) return value;
    return `"${value}"`;
  }
  
  if (typeof value === 'number') {
    return String(value);
  }
  
  return JSON.stringify(value);
}
