/**
 * Flutter/Dart Theme Exporter
 * 
 * Exports tokens as a Dart class for Flutter applications.
 */

import type { ExporterDefinition, NormalizedTokenSet } from '../token-pipeline';
import { toCamelCase, toPascalCase, sanitizeJsName, parseColor, colorToFlutter, dimensionToPx } from '../token-pipeline';

export const exportFlutter: ExporterDefinition = {
  id: 'flutter',
  name: 'Flutter / Dart',
  description: 'Dart theme class with typed color and dimension constants for Flutter.',
  category: 'mobile',
  extension: 'dart',
  mimeType: 'text/x-dart',
  isBinary: false,
  serverSide: false,
  subOptions: [
    {
      id: 'generateThemeData',
      label: 'Generate ThemeData',
      type: 'boolean',
      default: false,
    },
  ],
  export: (tokens: NormalizedTokenSet, options?: Record<string, any>): string => {
    const generateThemeData = options?.generateThemeData ?? false;
    const className = toPascalCase(sanitizeJsName(tokens.name)) || 'AppTheme';
    
    const lines: string[] = [
      `// Design Tokens: ${tokens.name}`,
      `// Generated by Visual DNA Studio`,
      `// W3C DTCG compliant - ${tokens.metadata.exportedAt}`,
      '',
      "import 'package:flutter/material.dart';",
      '',
      `class ${className} {`,
      `  ${className}._();`,
      '',
    ];
    
    const colorTokens = tokens.groups.color;
    if (colorTokens.length > 0) {
      lines.push('  // Colors');
      for (const token of colorTokens) {
        const dartName = toCamelCase(token.path.join('_'));
        if (typeof token.value === 'string') {
          const parsed = parseColor(token.value);
          if (parsed) {
            const dartColor = colorToFlutter(parsed);
            if (token.description) {
              lines.push(`  /// ${token.description}`);
            }
            lines.push(`  static const Color ${dartName} = ${dartColor};`);
          }
        }
      }
      lines.push('');
    }
    
    const dimensionTokens = [...tokens.groups.dimension, ...tokens.groups.spacing];
    if (dimensionTokens.length > 0) {
      lines.push('  // Dimensions');
      for (const token of dimensionTokens) {
        const dartName = toCamelCase(token.path.join('_'));
        const px = dimensionToPx(token.value);
        if (!isNaN(px)) {
          if (token.description) {
            lines.push(`  /// ${token.description}`);
          }
          lines.push(`  static const double ${dartName} = ${px};`);
        }
      }
      lines.push('');
    }
    
    const typographyTokens = tokens.groups.typography;
    if (typographyTokens.length > 0) {
      lines.push('  // Typography');
      for (const token of typographyTokens) {
        const dartName = toCamelCase(token.path.join('_'));
        if (token.type === 'fontFamily') {
          lines.push(`  static const String ${dartName} = "${token.value}";`);
        }
      }
      lines.push('');
    }
    
    if (generateThemeData && colorTokens.length > 0) {
      lines.push('  // Theme Data');
      lines.push('  static ThemeData get lightTheme => ThemeData(');
      lines.push('    useMaterial3: true,');
      
      const primaryColor = colorTokens.find(t => 
        t.path.some(p => p.toLowerCase().includes('primary'))
      );
      if (primaryColor) {
        const dartName = toCamelCase(primaryColor.path.join('_'));
        lines.push(`    primaryColor: ${dartName},`);
        lines.push(`    colorScheme: ColorScheme.fromSeed(seedColor: ${dartName}),`);
      }
      
      lines.push('  );');
      lines.push('');
    }
    
    lines.push('}');
    return lines.join('\n');
  },
};
