/**
 * Web Components Exporter
 * 
 * Exports tokens as CSS custom properties with Web Components integration.
 */

import type { ExporterDefinition, NormalizedTokenSet } from '../token-pipeline';
import { sanitizeCssName, parseColor, rgbaToCSS, dimensionToCSS } from '../token-pipeline';

export const exportWebComponents: ExporterDefinition = {
  id: 'web-components',
  name: 'Web Components',
  description: 'CSS custom properties optimized for Web Components with :host support.',
  category: 'web',
  extension: 'css',
  mimeType: 'text/css',
  isBinary: false,
  serverSide: false,
  subOptions: [
    {
      id: 'includeConstructableStylesheet',
      label: 'Include JS module wrapper',
      type: 'boolean',
      default: false,
    },
  ],
  export: (tokens: NormalizedTokenSet, options?: Record<string, any>): string => {
    const includeJS = options?.includeConstructableStylesheet ?? false;
    
    const cssLines: string[] = [];
    
    cssLines.push(`/* Design Tokens: ${tokens.name} */`);
    cssLines.push(`/* Generated by Visual DNA Studio */`);
    cssLines.push(`/* Web Components optimized */`);
    cssLines.push('');
    cssLines.push(':host {');
    
    for (const token of tokens.tokens) {
      const name = token.path.map(sanitizeCssName).join('-');
      const cssValue = formatCSSValue(token.value, token.type);
      cssLines.push(`  --${name}: ${cssValue};`);
    }
    
    cssLines.push('}');
    cssLines.push('');
    cssLines.push('/* Fallback for light DOM usage */');
    cssLines.push(':root {');
    
    for (const token of tokens.tokens) {
      const name = token.path.map(sanitizeCssName).join('-');
      const cssValue = formatCSSValue(token.value, token.type);
      cssLines.push(`  --${name}: ${cssValue};`);
    }
    
    cssLines.push('}');
    
    if (includeJS) {
      const jsLines: string[] = [
        `// Design Tokens: ${tokens.name}`,
        `// Generated by Visual DNA Studio`,
        `// Constructable Stylesheet for Web Components`,
        '',
        'const styles = new CSSStyleSheet();',
        'styles.replaceSync(`',
        ...cssLines,
        '`);',
        '',
        'export default styles;',
        '',
        '// Usage in your Web Component:',
        '// class MyComponent extends HTMLElement {',
        '//   constructor() {',
        '//     super();',
        '//     this.attachShadow({ mode: "open" });',
        '//     this.shadowRoot.adoptedStyleSheets = [styles];',
        '//   }',
        '// }',
      ];
      
      return jsLines.join('\n');
    }
    
    return cssLines.join('\n');
  },
};

function formatCSSValue(value: any, type: string): string {
  if (type === 'color' && typeof value === 'string') {
    const parsed = parseColor(value);
    if (parsed) {
      return rgbaToCSS(parsed);
    }
  }
  
  if (type === 'dimension') {
    return dimensionToCSS(value);
  }
  
  if (typeof value === 'string') {
    if (/^#[0-9a-fA-F]{3,8}$/.test(value)) return value;
    if (/^(rgb|hsl|oklch)/.test(value)) return value;
    if (/^-?\d+(\.\d+)?(px|rem|em|%|vw|vh|deg|s|ms)?$/.test(value)) return value;
    return `"${value}"`;
  }
  
  if (typeof value === 'number') {
    return String(value);
  }
  
  return JSON.stringify(value);
}
